const PERMISSIONS = {
    DASHBOARD_READ: "DASHBOARD_READ",

    EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
    EMPLOYEE_READ: "EMPLOYEE_READ",
    EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
    EMPLOYEE_DELETE: "EMPLOYEE_DELETE",

    ROLE_CREATE: "ROLE_CREATE",
    ROLE_READ: "ROLE_READ",
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_DELETE: "ROLE_DELETE",

    NODE_CREATE: "NODE_CREATE",
    NODE_READ: "NODE_READ",
    NODE_UPDATE: "NODE_UPDATE",
    NODE_DELETE: "NODE_DELETE",

    PATIENT_CREATE: "PATIENT_CREATE",
    PATIENT_READ: "PATIENT_READ",
    PATIENT_UPDATE: "PATIENT_UPDATE",
    PATIENT_DELETE: "PATIENT_DELETE",

    APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
    APPOINTMENT_READ: "APPOINTMENT_READ",
    APPOINTMENT_UPDATE: "APPOINTMENT_UPDATE",
    APPOINTMENT_DELETE: "APPOINTMENT_DELETE",
    APPOINTMENT_CANCEL: "APPOINTMENT_CANCEL",

    HEALTH_RECORD_CREATE: "HEALTH_RECORD_CREATE",
    HEALTH_RECORD_READ: "HEALTH_RECORD_READ",
    HEALTH_RECORD_UPDATE: "HEALTH_RECORD_UPDATE",
    HEALTH_RECORD_DELETE: "HEALTH_RECORD_DELETE"

};

module.exports = { PERMISSIONS };