sonar.projectKey=SPRINT-4
sonar.projectName=SPRINT-4
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
sonar.coverage.exclusions = **
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sonar.projectKey=HMS-SPRINT-3
sonar.projectName=HMS-SPRINT-3
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
sonar.coverage.exclusions = **
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sqp_4b39f6955183591e0f07b53e7edf44323e7ca23d