const STAFF_DESIGNATIONS = [
  "DOCTOR",
  "RECEPTIONIST",
  "CASHIER",
  "NURSE",
  "LAB_TECH",
  "PHARMACIST",
];

const DEPARTMENTS = [
  "OPD",
  "IPD",
  "Lab",
  "Pharmacy",
  "Administration",
  "Reception",
  "Billing",
];

const MEDICAL_DESIGNATIONS = ["DOCTOR", "NURSE", "PHARMACIST"];

const SPECIALIZATION_DESIGNATIONS = ["DOCTOR", "LAB_TECH"];

const RESTRICTED_ROLES = ["OWNER", "ADMIN"];

const DEPARTMENT_DESIGNATIONS = {
  OPD: ["DOCTOR", "NURSE"],
  IPD: ["DOCTOR", "NURSE"],
  Lab: ["LAB_TECH"],
  Pharmacy: ["PHARMACIST"],
  Reception: ["RECEPTIONIST"],
  Billing: ["CASHIER"],
  Administration: [],
};

const STAFF_DESIGNATIONS_SET = new Set(STAFF_DESIGNATIONS);
const DEPARTMENTS_SET = new Set(DEPARTMENTS);
const MEDICAL_DESIGNATIONS_SET = new Set(MEDICAL_DESIGNATIONS);
const SPECIALIZATION_DESIGNATIONS_SET = new Set(SPECIALIZATION_DESIGNATIONS);
const RESTRICTED_ROLES_SET = new Set(RESTRICTED_ROLES);

module.exports = {
  STAFF_DESIGNATIONS,
  DEPARTMENTS,
  MEDICAL_DESIGNATIONS,
  SPECIALIZATION_DESIGNATIONS,
  RESTRICTED_ROLES,
  DEPARTMENT_DESIGNATIONS,
  STAFF_DESIGNATIONS_SET,
  DEPARTMENTS_SET,
  MEDICAL_DESIGNATIONS_SET,
  SPECIALIZATION_DESIGNATIONS_SET,
  RESTRICTED_ROLES_SET,
};
