sonar.projectKey=hms_frontend
sonar.projectName=hms_frontend
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
sonar.coverage.exclusions=**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sqp_dfa68d3a53d3a8d433d992a4e69dac4d8c0268f1