sonar.projectKey=hms-angular
sonar.projectName=hms-angular
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# exclude all tests to temporarily disable coverage testing
sonar.coverage.exclusions=**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.token=sqp_c6353e9ac71dd623fcd487f67441bb01ed261ee9