sonar.projectKey=hms_frontend
sonar.projectName=hms_frontend
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sqp_5ee72889cdbde5d9d77520e8831e11e6f8d714d0 

sonar.coverage.exclusions = **