name: Deploy HMS Backend

on:
  push:
    branches:
      - feature/sprint_5/arjun

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd hms-backend-pod-3
            git pull origin feature/sprint_5/arjun
            sudo npm ci
            pm2 restart hms-backend || pm2 start src/server.js --name hms-backend
            pm2 save