name: Deploy HMS Backend

on:
  push:
    branches:
      - feature/sprint5_pod4_jaishruthie

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_JAISHRUTHIE_HOST }}
          username: ${{ secrets.EC2_JAISHRUTHIE_USER }}
          key: ${{ secrets.EC2_JAISHRUTHIE_KEY }}
          script: |
            sudo su root
            cd hms_main_project/HMS_POD_4
            git pull origin feature/sprint5_pod4_jaishruthie
            cd Backend
            npm ci
            pm2 restart Backend || pm2 start server.js --name Backend
            pm2 save

            echo "Deploying Angular..."

            cd ../Angular

            npm ci

            npm run build -- --configuration production

            sudo rm -rf /var/www/angular/*

            sudo cp -r dist/FRONTEND/browser/* /var/www/angular/

            sudo systemctl restart nginx

            echo "Deployment completed successfully."